apiVersion: v1
kind: Service
metadata:
  name: xeon-vllm
  namespace: xeon-vllm
spec:
  selector:
    app: xeon-vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
