apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xeon-vllm
  namespace: xeon-vllm
spec:
  selector:
    matchLabels:
      app: xeon-vllm
  endpoints:
    - port: http
      interval: 5s
